version: '3.9'

services:
  maven:
    profiles:
      - production
    build:
      context: .
      dockerfile: .docker/mvn/Dockerfile
    user: root  # Pour avoir le droit de changer les permissions
    volumes:
      - .:/app
      - .docker/m2:/root/.m2
    container_name: maven-builder
    command: sh -c "chown -R ${UID}:${GID} /app && /usr/bin/mvn clean install"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vaadin-springboot-app
    ports:
      # Utilisation d'une variable d'environnement pour choisir les ports dynamiquement
      - "${APP_PORT}:8080"
    volumes:
      - .:/app
      - target-data:/app/target
      - .docker/m2:/root/.m2
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      # Utilisation d'une variable d'environnement pour choisir le port MySQL
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  target-data:
  mysql-data:
