name: Déploiement en Production

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'prod' &&
      github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Démarrer l'agent SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Déploiement sur le serveur de production
        run: |
          ssh -o StrictHostKeyChecking=no deploy@${{ secrets.PROD_HOST }} -p 2223 << 'EOF'
          # Se déplacer dans le répertoire du projet
          cd ${{ secrets.PROD_APP_PATH }}
        
          # Arrêter les services Docker Compose en cours d'exécution
          docker-compose down
        
          # Vérifier si le répertoire est déjà un dépôt git
          if [ ! -d .git ]; then
          echo "Dépôt Git non trouvé, clonage du dépôt..."
          git clone git@github.com:ldesfontaine/projet10.git .
          else
          sudo -n chown -R deploy:deploy .
          echo "Dépôt Git trouvé, mise à jour du dépôt..."
          git pull origin prod
          fi
        
          # Démarrer ou redémarrer les services via Docker Compose
          docker-compose --profile production up -d
          EOF
        env:
          PROD_HOST: ${{ secrets.PROD_HOST }}
          PROD_APP_PATH: ${{ secrets.PROD_APP_PATH }}

